### ISSUE TITLE
Error 403 when converting ChatGPT to API

### ISSUE THREAD

**Issue by popflag** [gngpp/opengpt#109]
Experiencing a 403 error when transitioning from ChatGPT to API, only affects GPT4; GPT3 is unaffected.

error response
```
{
  "code": "403",
  "msg": "HTTP status client error (403 Forbidden) for url (https://chat.openai.com/backend-api/conversation)"
}
```

**Comment by gngpp** [comment]
You need to provide the endpoint for obtaining `arkose token` by yourself, and add the parameter `--arkose-token-endpoint https://chatarkose.xyhelper.cn/token` when starting, the above is to use free public nodes, this project can let You build `arkose token` endpoint by yourself: `https://github.com/xyhelper/xyhelper-arkose-v2`

**Comment by popflag** [comment]
Thanks.
