### ISSUE TITLE
牛逼

### ISSUE THREAD

**Issue by 18230** [gngpp/opengpt#57]
老哥这个怎么编译的  ubuntu直接装上就能跑吗？

**Comment by gngpp** [comment]
已经有预编译的了，直接用

**Comment by 18230** [comment]
老哥有V 吗 ，加个

**Comment by 18230** [comment]
把你拉群里，一起讨论

**Comment by gngpp** [comment]
![mmqrcode1689547585457.png](https://github.com/gngpp/opengpt/assets/51810656/c01178de-47ac-48e2-ba4a-48146689c579)
